namespace Everything.LowLevel
{
  public class Sort
  {
    public const int EVERYTHING_SORT_NAME_ASCENDING = 1;
    public const int EVERYTHING_SORT_NAME_DESCENDING = 2;
    public const int EVERYTHING_SORT_PATH_ASCENDING = 3;
    public const int EVERYTHING_SORT_PATH_DESCENDING = 4;
    public const int EVERYTHING_SORT_SIZE_ASCENDING = 5;
    public const int EVERYTHING_SORT_SIZE_DESCENDING = 6;
    public const int EVERYTHING_SORT_EXTENSION_ASCENDING = 7;
    public const int EVERYTHING_SORT_EXTENSION_DESCENDING = 8;
    public const int EVERYTHING_SORT_TYPE_NAME_ASCENDING = 9;
    public const int EVERYTHING_SORT_TYPE_NAME_DESCENDING = 10;
    public const int EVERYTHING_SORT_DATE_CREATED_ASCENDING = 11;
    public const int EVERYTHING_SORT_DATE_CREATED_DESCENDING = 12;
    public const int EVERYTHING_SORT_DATE_MODIFIED_ASCENDING = 13;
    public const int EVERYTHING_SORT_DATE_MODIFIED_DESCENDING = 14;
    public const int EVERYTHING_SORT_ATTRIBUTES_ASCENDING = 15;
    public const int EVERYTHING_SORT_ATTRIBUTES_DESCENDING = 16;
    public const int EVERYTHING_SORT_FILE_LIST_FILENAME_ASCENDING = 17;
    public const int EVERYTHING_SORT_FILE_LIST_FILENAME_DESCENDING = 18;
    public const int EVERYTHING_SORT_RUN_COUNT_ASCENDING = 19;
    public const int EVERYTHING_SORT_RUN_COUNT_DESCENDING = 20;
    public const int EVERYTHING_SORT_DATE_RECENTLY_CHANGED_ASCENDING = 21;
    public const int EVERYTHING_SORT_DATE_RECENTLY_CHANGED_DESCENDING = 22;
    public const int EVERYTHING_SORT_DATE_ACCESSED_ASCENDING = 23;
    public const int EVERYTHING_SORT_DATE_ACCESSED_DESCENDING = 24;
    public const int EVERYTHING_SORT_DATE_RUN_ASCENDING = 25;
    public const int EVERYTHING_SORT_DATE_RUN_DESCENDING = 26;
  }
}
